:github-readme: ../README.adoc

include::{github-readme}[tags=vardef]

:bintraypage: https://bintray.com/jmini/maven/asciidoctorj-gh-edit
:projectpage: https://github.com/{gh-repo-owner}/{gh-repo-name}

include::{github-readme}[tags=header]

== URLs

* link:{homepage}[Project home] (this page)
* link:{projectpage}[GitHub project]
//* link:{bintraypage}[Binaries on Bintray]
* link:{issues}[Issue tracker]

TIP: Do you want to improve this page? Please gh:edit[link-text='edit it on GitHub'].

include::{github-readme}[tags=description]

=== Asciidoctor Test suite

The `adoc-test-cases` project contains the asciidoctor test suite used by other projects of this repository.
For each test case, following elements are provided:

* the AsciiDoc source input
* the input options map used to run asciidoctor
* the expected html output
* some java code (written with link:http://joel-costigliola.github.io/assertj/[AssertJ]) to ensure that the AST corresponding to the input source and options is well-formed.
* some link:http://site.mockito.org/[Mockito] Java code to produce the corresponding AST, without having to parse the AsciiDoc input and without having to rely on the JRuby bridge.

Each test case implements the gh:viewfile[path='test-cases/adoc-test-cases/src/main/java/fr/jmini/asciidoctorj/testcases/AdocTestCase.java', link-text='AdocTestCase'] interface.

For each test case, a AsciiDoc file is also provided in the gh:viewdir[path='test-cases/adoc-test-cases/src/main/resources', link-text='resources'] folder.
This can be usefull to preview the test case in a web-browser.

The gh:viewfile[path='test-cases/adoc-test-cases/src/main/java/fr/jmini/asciidoctorj/testcases/AdocTestCases.java', link-text='AdocTestCases'] class provides a list of each test cases with the `getAllTestCases()` method.


=== AST Conveters

Some converters for the Asciidoctor AST.

==== ast-json

This is an attempt to create a JSON output of the AST of the document.
(see link:http://discuss.asciidoctor.org/Asciidoctor-AST-output-td4670.html[this discussion] on the mailing list)

The main class is gh:view[path='ast-json/src/main/java/ast/json/AstJsonConverter.java', link-text='AstJsonConverter'].
It can be registered and used like this:
[source,java,indent=0]
----
include::../ast-json/src/main/java/ast/json/Main.java[tags='adoc-convert']
----

I have tried to run it on several examples provided in this folder
gh:viewdir[path='ast-json/examples', link-text='examples'].

==== assert-code

Some AssertJ code (suitable for usage is a JUnit test case) is generated for a given instance of the Asciidoctor AST.
The output of this converted is a `checkAst(..)` Method.
This method will call each method of the AST Object (the complete tree will be traversed) and will expected some method for each method call.
The generated assertions are valid for the instance used as input.

Take this AsciiDoc snippet as input example:

[source, adoc]
----
include::../code-converter/mock-code-converter/src/test/java/fr/jmini/asciidoctorj/converter/mockcode/MockCodeGeneratorExampleTest.java[tags="input"]
----

When the AsciiDoc Text in is loaded as Asciidoctor AST using the `Asciidoctor.load(String, Map<String, Object>)` method, the output of the converter will be this method:

[source, java]
----
include::../code-converter/assert-code-converter/src/test/java/fr/jmini/asciidoctorj/converter/assertcode/AssertCodeGeneratorExampleTest.java[tags="generated-code"]
----

==== mock-code

In order to be able to replay some JUnit Tests without having to parse AsciiDoc text to produce the AST (JRuby is slow), a solution might be to create an Instance of the AST with Mockito.
Writing the code to create the mock manually is not really interesting.

The *mock-code* converter can generate the code to initialize the mock for a given AST instance.
The output of this converted is a `createMock()` method.
This method will return a mocked implementation for AST interface corresponding to the AST instance used as input.
The behaviour for the majority of methods in the mock are defined.
In particular it is possible to traverse the tree.

Take this AsciiDoc snippet as input example:

[source, adoc]
----
include::../code-converter/mock-code-converter/src/test/java/fr/jmini/asciidoctorj/converter/mockcode/MockCodeGeneratorExampleTest.java[tags="input"]
----

When the AsciiDoc Text in is loaded as Asciidoctor AST using the `Asciidoctor.load(String, Map<String, Object>)` method, the output of the converter will be this method:

[source, java]
----
include::../code-converter/mock-code-converter/src/test/java/fr/jmini/asciidoctorj/converter/mockcode/MockCodeGeneratorExampleTest.java[tags="generated-code"]
----

=== html2adoc

This is a converter from HTML to AsciiDoc.
It is using JSoup to parse the HTML.

include::{github-readme}[tags=contact-section]

include::{github-readme}[tags=license-section]

